name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Europe/Paris
